import {type ReactElement} from 'react';
import {cl} from '@builtbymom/web3/utils';

import {newDisperseVoidRow} from '../disperse/useDisperse.helpers';
import {useDisperse} from './contexts/useDisperse';
import {IconPlus} from './icons/IconPlus';

export function AddReceiverCard({className}: {className?: string}): ReactElement {
	const {dispatchConfiguration} = useDisperse();

	/**********************************************************************************************
	 ** onAddReceivers function adds a specified number of new receiver entries to the configuration.
	 ** It dispatches an 'ADD_RECEIVERS' action with a payload containing an array of new
	 ** disperse void rows, generated by the newDisperseVoidRow function.
	 *********************************************************************************************/
	const onAddReceivers = (amount: number): void => {
		dispatchConfiguration({
			type: 'ADD_RECEIVERS',
			payload: Array(amount)
				.fill(null)
				.map(() => newDisperseVoidRow())
		});
	};

	return (
		<button
			onClick={() => {
				onAddReceivers(1);
			}}
			className={cl(
				'flex h-[152px] flex-col items-center justify-center',
				'gap-2 rounded-3xl border border-accent bg-background-modal/90',
				'hover:bg-primary/10',
				className
			)}>
			<IconPlus className={'size-6 text-primary'} />
			<span>{'Add receiver'}</span>
		</button>
	);
}
