import {useDisperse} from './common/contexts/useDisperse';
import {DownloadTemplateButton} from './common/DownloadTemplateButton';
import {ExportConfigurationButton} from './common/ExportConfigurationButton';
import {IconPlus} from './common/icons/IconPlus';
import {ImportConfigurationButton} from './common/ImportConfigurationButton';
import {newDisperseVoidRow} from './disperse/useDisperse.helpers';

import type {ReactElement} from 'react';

export function Controls(): ReactElement | null {
	const {configuration, dispatchConfiguration} = useDisperse();
	if (configuration.inputs.length < 1) {
		return null;
	}

	/**********************************************************************************************
	 ** onAddReceivers function adds a specified number of new receivers to the configuration state.
	 ** It dispatches an action of type 'ADD_RECEIVERS' with a payload that is an array of new
	 ** receiver objects. Еhe array is created by filling it with null values and then mapping each
	 ** one to a new receiver object generated by the newDisperseVoidRow function.
	 ** The 'amount' parameter specifies how many new receivers should be added.
	 *********************************************************************************************/
	const onAddReceivers = (amount: number): void => {
		dispatchConfiguration({
			type: 'ADD_RECEIVERS',
			payload: Array(amount)
				.fill(null)
				.map(() => newDisperseVoidRow())
		});
	};

	return (
		<div className={'my-10 flex w-full justify-between px-6 md:mt-[100px] md:px-0'}>
			<div className={'grid grid-cols-2 gap-4 md:flex md:gap-2'}>
				<ImportConfigurationButton className={'!bg-primary !text-secondary hover:!bg-primary/90'} />
				<ExportConfigurationButton className={'hover:!bg-primary/90'} />
				<DownloadTemplateButton className={'hover:bg-primary/20'} />
			</div>
			<div className={'hidden md:flex'}>
				<button
					onClick={() => onAddReceivers(1)}
					className={
						'flex items-center gap-2 rounded-lg bg-primary p-2 font-bold text-secondary hover:!bg-primary/90'
					}>
					<IconPlus className={'size-4'} />
					{'Add receiver'}
				</button>
			</div>
		</div>
	);
}
